#!/usr/bin/env bash
# nix/check-cli-module-placement.sh
#
# Enforces the CLI library-first module-placement convention. See
# docs/dev/architecture/overview.md, section "CLI Module Placement
# Convention", for the rule. Reads seihou-cli/seihou-cli.cabal, walks
# the executable's other-modules, and fails if an entry is not
# justifiably executable-only — i.e. it does not import one of the
# four executable-only Haskell-package dependencies
# (Options.Applicative, Data.FileEmbed, GitHash, Paths_seihou_cli)
# and is not transitively trapped by importing another trapped seihou
# module (most often Seihou.CLI.Commands).

set -euo pipefail

# Locate the repo root. Three callers exercise this path:
#   1. Direct invocation from the repo root (most common).
#   2. `pkgs.runCommand` in flake.nix, which `cd`s into the copied source.
#   3. The pre-commit hook, where the script lives in /nix/store/... but
#      pre-commit sets the working directory to the repo root.
# The script-location fallback (`BASH_SOURCE[0]/..`) is wrong in case 3,
# so prefer `$PWD` whenever it looks like a seihou checkout.
if [[ -n "${SEIHOU_REPO_ROOT:-}" ]]; then
  REPO_ROOT="$SEIHOU_REPO_ROOT"
elif [[ -f "$PWD/seihou-cli/seihou-cli.cabal" ]]; then
  REPO_ROOT="$PWD"
else
  REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
CABAL_FILE="${REPO_ROOT}/seihou-cli/seihou-cli.cabal"
EXE_SRC_DIR="${REPO_ROOT}/seihou-cli/src-exe"
DOC_REF='docs/dev/architecture/overview.md, section "CLI Module Placement Convention"'

# Modules that legitimately stay in the executable target despite not
# matching the import-based heuristic. Add to this list with an inline
# comment justifying the exemption.
EXEMPT_MODULES=(
  "Paths_seihou_cli"            # auto-generated by Cabal; no source file on disk
  "Seihou.CLI.AgentLaunchExec"  # process-launcher (rawSystem/exitWith) consumed only by trapped agent-prompt wrappers (Assist/Bootstrap/Setup); kept executable-side by design (see EP-3, docs/plans/20-extract-trapped-cli-helpers.md)
)

# Step 1: extract the executable's other-modules list. The cabal file's
# executable stanza begins with "^executable seihou" at column 0; its
# fields are indented two spaces; module names within other-modules are
# indented four spaces.
extract_executable_other_modules() {
  awk '
    /^executable seihou[[:space:]]*$/ { in_exec = 1; next }
    in_exec && /^[a-zA-Z]/            { in_exec = 0 }
    in_exec && /^  other-modules:/    { in_om = 1; next }
    in_exec && in_om && /^  [a-zA-Z]/ { in_om = 0 }
    in_om && /^    [A-Za-z]/ {
      gsub(/[ \t]+/, "")
      sub(/--.*$/, "")
      if (length($0) > 0) print
    }
  ' "$CABAL_FILE"
}

# Map a module name (e.g. Seihou.CLI.Foo) to its source path under
# src-exe/. Prints nothing if the file does not exist (e.g. the
# auto-generated Paths_seihou_cli).
module_to_path() {
  local mod="$1"
  local rel="${mod//./\/}.hs"
  local path="${EXE_SRC_DIR}/${rel}"
  if [[ -f "$path" ]]; then
    echo "$path"
  fi
}

# True if the file at $1 has a top-level import of one of the four
# executable-only Haskell-package dependencies.
has_direct_exec_only_import() {
  local path="$1"
  if [[ -z "$path" ]]; then
    return 1
  fi
  grep -E '^import (qualified )?(Options\.Applicative|Data\.FileEmbed|GitHash|Paths_seihou_cli)([[:space:]]|$)' \
    "$path" >/dev/null
}

# List the seihou modules a file imports, one per line. Strips
# "qualified" and any import list / "as Alias" suffix.
seihou_imports() {
  local path="$1"
  grep -E '^import (qualified )?Seihou\.' "$path" \
    | sed -E 's/^import (qualified )?//' \
    | awk '{print $1}'
}

# Compute the closure of executable-only modules under src-exe/.
# Seeds with directly-trapped modules; iteratively adds any src-exe
# module that imports an already-trapped one. Library modules under
# src/ never enter the set: they cannot import src-exe modules
# (cycle), and library-private placement keeps them off the four
# trapping deps.
compute_closure() {
  local -a all_modules=()
  while IFS= read -r mod; do
    all_modules+=("$mod")
  done < <(
    find "$EXE_SRC_DIR" -name '*.hs' -print \
      | sed -e "s|^${EXE_SRC_DIR}/||" -e 's|/|.|g' -e 's|\.hs$||' \
      | grep -v '^Main$'
  )

  local -A trapped=()
  for mod in "${all_modules[@]}"; do
    local path
    path=$(module_to_path "$mod")
    if has_direct_exec_only_import "$path"; then
      trapped["$mod"]=1
    fi
  done

  local changed=1
  while [[ $changed -eq 1 ]]; do
    changed=0
    for mod in "${all_modules[@]}"; do
      if [[ -n "${trapped[$mod]:-}" ]]; then
        continue
      fi
      local path
      path=$(module_to_path "$mod")
      if [[ -z "$path" ]]; then
        continue
      fi
      while IFS= read -r imp; do
        if [[ -n "${trapped[$imp]:-}" ]]; then
          trapped["$mod"]=1
          changed=1
          break
        fi
      done < <(seihou_imports "$path")
    done
  done

  for mod in "${!trapped[@]}"; do
    echo "$mod"
  done | sort
}

main() {
  if [[ ! -f "$CABAL_FILE" ]]; then
    echo "ERROR: cabal file not found at $CABAL_FILE" >&2
    exit 2
  fi
  if [[ ! -d "$EXE_SRC_DIR" ]]; then
    echo "ERROR: executable source dir not found at $EXE_SRC_DIR" >&2
    exit 2
  fi

  local closure
  closure=$(compute_closure)

  local -a violations=()
  local total=0
  while IFS= read -r mod; do
    total=$((total + 1))
    local exempt=0
    for ex in "${EXEMPT_MODULES[@]}"; do
      if [[ "$mod" == "$ex" ]]; then
        exempt=1
        break
      fi
    done
    if [[ $exempt -eq 1 ]]; then
      continue
    fi
    if printf '%s\n' "$closure" | grep -Fxq "$mod"; then
      continue
    fi
    violations+=("$mod")
  done < <(extract_executable_other_modules)

  if [[ $total -eq 0 ]]; then
    echo "ERROR: parsed zero entries from executable's other-modules." >&2
    echo "       Check the awk parser in this script against the cabal file's format." >&2
    exit 2
  fi

  if [[ ${#violations[@]} -eq 0 ]]; then
    echo "OK: ${total} modules in executable other-modules, all justified."
    exit 0
  fi

  echo "FAIL: ${#violations[@]} module(s) in executable other-modules"
  echo "      have no recognised trapping dependency."
  echo
  echo "Violations:"
  for v in "${violations[@]}"; do
    echo "  - ${v}"
  done
  echo
  echo "Each module in 'executable seihou' must either:"
  echo "  1. Import one of: Options.Applicative, Data.FileEmbed,"
  echo "     GitHash, Paths_seihou_cli."
  echo "  2. Import a module that is already executable-only"
  echo "     (transitive trap, e.g. via Seihou.CLI.Commands)."
  echo "  3. Appear in EXEMPT_MODULES at the top of"
  echo "     ${BASH_SOURCE[0]}."
  echo
  echo "If the module is genuinely a pure helper, move it to"
  echo "library seihou-cli-internal's exposed-modules in"
  echo "seihou-cli/seihou-cli.cabal (source under seihou-cli/src/)."
  echo
  echo "Rule: ${DOC_REF}."
  exit 1
}

main "$@"
