{ name = "haskell-shared-readme"
, version = None Text
, description = Some "Appends a section to the README generated by haskell-base"
, vars = [] : List { name : Text, type : Text, default : Optional Text, description : Optional Text, required : Bool, validation : Optional Text }
, exports = [] : List { var : Text, alias : Optional Text }
, prompts = [] : List { var : Text, text : Text, when : Optional Text, choices : Optional (List Text) }
, steps =
  [ { strategy = "template"
    , src = "readme-section.md.tpl"
    , dest = "README.md"
    , when = None Text
    , patch = Some "append-section"
    }
  ]
, commands = [] : List { run : Text, workDir : Optional Text, when : Optional Text }
, dependencies = [ { module = "haskell-base", vars = [] : List { name : Text, value : Text } } ]
, removal = None { steps : List { action : Text, dest : Text, src : Optional Text }, commands : List { run : Text, workDir : Optional Text, when : Optional Text } }
}
