module Seihou.Engine.Diff
  ( computeDiff,
    planToFileMap,
  )
where

import Data.Map.Strict (Map)
import Data.Map.Strict qualified as Map
import Data.Set qualified as Set
import Data.Text (Text)
import Effectful
import Seihou.Core.Types
import Seihou.Effect.Filesystem (Filesystem, doesFileExist, readFileText)
import Seihou.Manifest.Hash (hashContent)

-- | Extract a map of (path, content) from planned operations.
-- Only WriteFileOp and CopyFileOp produce file entries; directories and
-- commands are ignored.
planToFileMap :: [Operation] -> Map FilePath Text
planToFileMap = Map.fromList . concatMap extract
  where
    extract (WriteFileOp dest content) = [(dest, content)]
    extract _ = []

-- | Compute a three-state diff: manifest vs plan vs disk.
-- Classifies each file into one of: New, Modified, Unchanged, Conflict, Orphaned.
computeDiff ::
  (Filesystem :> es) =>
  Manifest ->
  [(FilePath, Text, ModuleName)] ->
  Eff es DiffResult
computeDiff manifest planned = do
  let manifestFiles' = manifestFiles manifest
      planMap = Map.fromList [(p, (content, modName)) | (p, content, modName) <- planned]
      allPaths =
        Set.toList $
          Set.union
            (Map.keysSet manifestFiles')
            (Map.keysSet planMap)

  results <- mapM (classifyFile manifestFiles' planMap) allPaths

  let newFiles = [f | ClassNew f <- results]
      modifiedFiles = [f | ClassModified f <- results]
      unchangedFiles = [f | ClassUnchanged f <- results]
      conflictFiles = [f | ClassConflict f <- results]
      orphanedFiles = [f | ClassOrphaned f <- results]

  pure
    DiffResult
      { diffNew = newFiles,
        diffModified = modifiedFiles,
        diffUnchanged = unchangedFiles,
        diffConflict = conflictFiles,
        diffOrphaned = orphanedFiles
      }

data Classification
  = ClassNew PlannedFile
  | ClassModified ModifiedFile
  | ClassUnchanged FilePath
  | ClassConflict ConflictFile
  | ClassOrphaned OrphanedFile

classifyFile ::
  (Filesystem :> es) =>
  Map FilePath FileRecord ->
  Map FilePath (Text, ModuleName) ->
  FilePath ->
  Eff es Classification
classifyFile manifestFiles' planMap path = do
  let inManifest = Map.lookup path manifestFiles'
      inPlan = Map.lookup path planMap
  onDisk <- doesFileExist path

  case (inManifest, inPlan, onDisk) of
    -- In plan, not in manifest, not on disk → New
    (Nothing, Just (content, modName), False) ->
      pure $ ClassNew (PlannedFile path modName content)
    -- In plan, not in manifest, on disk → Conflict (file exists but wasn't generated by us)
    (Nothing, Just (content, modName), True) -> do
      diskContent <- readFileText path
      let diskHash = hashContent diskContent
      pure $
        ClassConflict
          ( ConflictFile
              { conflictPath = path,
                conflictModule = modName,
                conflictManifest = SHA256 "",
                conflictDisk = diskHash,
                conflictPlan = content
              }
          )
    -- In manifest + plan + disk
    (Just record, Just (content, modName), True) -> do
      diskContent <- readFileText path
      let diskHash = hashContent diskContent
          manifestHash = fileHash record
          planHash = hashContent content
      if diskHash /= manifestHash
        then -- User modified the file → Conflict
          pure $
            ClassConflict
              ( ConflictFile
                  { conflictPath = path,
                    conflictModule = modName,
                    conflictManifest = manifestHash,
                    conflictDisk = diskHash,
                    conflictPlan = content
                  }
              )
        else
          if planHash == manifestHash
            then pure $ ClassUnchanged path
            else
              pure $
                ClassModified
                  ( ModifiedFile
                      { modifiedPath = path,
                        modifiedModule = modName,
                        modifiedOldHash = manifestHash,
                        modifiedNewContent = content
                      }
                  )
    -- In manifest + plan, not on disk → treat as Modified (file was deleted by user, re-create)
    (Just record, Just (content, modName), False) ->
      pure $
        ClassModified
          ( ModifiedFile
              { modifiedPath = path,
                modifiedModule = modName,
                modifiedOldHash = fileHash record,
                modifiedNewContent = content
              }
          )
    -- In manifest, not in plan, on disk → Orphaned
    (Just record, Nothing, True) ->
      pure $ ClassOrphaned (OrphanedFile path (fileModule record))
    -- In manifest, not in plan, not on disk → Orphaned (already deleted)
    (Just record, Nothing, False) ->
      pure $ ClassOrphaned (OrphanedFile path (fileModule record))
    -- Not in manifest, not in plan → shouldn't happen (we only iterate known paths)
    (Nothing, Nothing, _) ->
      pure $ ClassUnchanged path -- unreachable in practice
