module Seihou.Core.Scaffold
  ( moduleDhall,
    readmeTemplate,
  )
where

import Data.Text (Text)
import Data.Text qualified as T

-- | Generate the module.dhall content for a new module.
-- The output matches the Dhall schema expected by 'Seihou.Dhall.Eval.moduleDecoder'.
moduleDhall :: Text -> Text
moduleDhall name =
  T.unlines
    [ "{ name = \"" <> name <> "\"",
      ", description = Some \"A new seihou module\"",
      ", vars =",
      "  [ { name = \"project.name\"",
      "    , type = \"text\"",
      "    , default = None Text",
      "    , description = Some \"The name of the project\"",
      "    , required = True",
      "    , validation = None Text",
      "    }",
      "  ]",
      ", exports = [] : List { var : Text, alias : Optional Text }",
      ", prompts =",
      "  [ { var = \"project.name\"",
      "    , text = \"What is your project name?\"",
      "    , when = None Text",
      "    , choices = None (List Text)",
      "    }",
      "  ]",
      ", steps =",
      "  [ { strategy = \"template\"",
      "    , src = \"README.md.tpl\"",
      "    , dest = \"README.md\"",
      "    , when = None Text",
      "    , patch = None Text",
      "    }",
      "  ]",
      ", commands = [] : List { run : Text, workDir : Optional Text, when : Optional Text }",
      ", dependencies = [] : List Text",
      "}"
    ]

-- | Generate the README.md.tpl template content.
readmeTemplate :: Text
readmeTemplate = "# {{project.name}}\n\nA project generated by seihou.\n"
