module Seihou.Core.Scaffold
  ( moduleDhall,
    readmeTemplate,
  )
where

import Data.Text qualified as T
import Seihou.Prelude

-- | Generate the module.dhall content for a new module.
-- The output imports the schema via URL and uses record completion (::).
moduleDhall :: Text -> Text -> Text -> Text
moduleDhall name url hash =
  T.unlines
    [ "let S =",
      "      " <> url,
      "        " <> hash,
      "",
      "in  S.Module::{",
      "    , name = \"" <> name <> "\"",
      "    , version = Some \"0.1.0\"",
      "    , description = Some \"A new seihou module\"",
      "    , vars =",
      "      [ S.VarDecl::{",
      "        , name = \"project.name\"",
      "        , type = \"text\"",
      "        , description = Some \"The name of the project\"",
      "        , required = True",
      "        }",
      "      ]",
      "    , prompts =",
      "      [ S.Prompt::{",
      "        , var = \"project.name\"",
      "        , text = \"What is your project name?\"",
      "        }",
      "      ]",
      "    , steps =",
      "      [ S.Step::{",
      "        , strategy = \"template\"",
      "        , src = \"README.md.tpl\"",
      "        , dest = \"README.md\"",
      "        }",
      "      ]",
      "    }"
    ]

-- | Generate the README.md.tpl template content.
readmeTemplate :: Text
readmeTemplate = "# {{project.name}}\n\nA project generated by seihou.\n"
