module Seihou.CLI.NewModule
  ( handleNewModule,
  )
where

import Data.Text (Text)
import Data.Text qualified as T
import Data.Text.IO qualified as TIO
import Seihou.CLI.Commands (NewModuleOpts (..))
import Seihou.CLI.Shared (logIO)
import Seihou.Core.Types (LogLevel (..))
import Seihou.Effect.Logger (logError)
import System.Directory (createDirectoryIfMissing, doesDirectoryExist)
import System.Exit (exitFailure)
import System.FilePath ((</>))

handleNewModule :: NewModuleOpts -> IO ()
handleNewModule nopts = do
  let name = newModuleName nopts

  -- Validate module name format
  if not (isValidModuleName name)
    then do
      logIO LogNormal $ do
        logError $ "invalid module name '" <> name <> "'."
        logError "Module names must match [a-z][a-z0-9-]*."
      exitFailure
    else pure ()

  -- Determine output directory
  let outputDir = case newModulePath nopts of
        Just p -> p
        Nothing -> T.unpack name

  -- Check that the target directory does not already exist
  exists <- doesDirectoryExist outputDir
  if exists
    then do
      logIO LogNormal (logError $ "directory '" <> T.pack outputDir <> "' already exists.")
      exitFailure
    else pure ()

  -- Create directory structure
  createDirectoryIfMissing True (outputDir </> "files")

  -- Write module.dhall
  let dhallContent = moduleDhall name
  writeFile (outputDir </> "module.dhall") (T.unpack dhallContent)
  TIO.putStrLn $ "Created " <> T.pack (outputDir </> "module.dhall")

  -- Write files/README.md.tpl
  let templateContent = readmeTemplate
  writeFile (outputDir </> "files" </> "README.md.tpl") (T.unpack templateContent)
  TIO.putStrLn $ "Created " <> T.pack (outputDir </> "files" </> "README.md.tpl")

  TIO.putStrLn $ "Module '" <> name <> "' created at " <> T.pack outputDir <> "/"

-- | Check if a module name matches [a-z][a-z0-9-]*
isValidModuleName :: Text -> Bool
isValidModuleName t = case T.uncons t of
  Nothing -> False
  Just (c, rest) ->
    (c >= 'a' && c <= 'z')
      && T.all (\ch -> (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '-') rest

-- | Generate the module.dhall content for a new module
moduleDhall :: Text -> Text
moduleDhall name =
  T.unlines
    [ "{ name = \"" <> name <> "\"",
      ", description = Some \"A new seihou module\"",
      ", variables =",
      "  [ { name = \"project.name\"",
      "    , type = \"text\"",
      "    , default = None Text",
      "    , description = Some \"The name of the project\"",
      "    , required = True",
      "    , validation = None Text",
      "    }",
      "  ]",
      ", exports = [] : List { var : Text, as : Optional Text }",
      ", prompts =",
      "  [ { var = \"project.name\"",
      "    , text = \"What is your project name?\"",
      "    , when = None Text",
      "    , choices = None (List Text)",
      "    }",
      "  ]",
      ", steps =",
      "  [ { strategy = \"template\"",
      "    , src = \"README.md.tpl\"",
      "    , dest = \"README.md\"",
      "    , when = None Text",
      "    }",
      "  ]",
      ", dependencies = [] : List Text",
      "}"
    ]

-- | Generate the README.md.tpl template content
readmeTemplate :: Text
readmeTemplate = "# {{project.name}}\n\nA project generated by seihou.\n"
